### ISSUE TITLE
不兼容部署在mac mini上？

### ISSUE THREAD

**Issue by lylh** [reliablejs/reliable-master#18]
> Step 6 : RUN wget http://download.zeromq.org/zeromq-$ZEROMQ_VERSION.tar.gz 	&& tar -zxvf zeromq-$ZEROMQ_VERSION.tar.gz 	&& cd ./zeromq-$ZEROMQ_VERSION 	&& ./configure && make && make install 	&& ldconfig
 ---> Running in 546ec6b82c09
converted 'http://download.zeromq.org/zeromq-4.1.3.tar.gz' (ANSI_X3.4-1968) -> 'http://download.zeromq.org/zeromq-4.1.3.tar.gz' (UTF-8)
--2016-06-06 03:17:57--  http://download.zeromq.org/zeromq-4.1.3.tar.gz
Resolving download.zeromq.org (download.zeromq.org)... 52.90.174.192
Connecting to download.zeromq.org (download.zeromq.org)|52.90.174.192|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-06-06 03:17:58 ERROR 404: Not Found.

ERROR: Service 'reliable-master' failed to build: The command '/bin/sh -c wget http://download.zeromq.org/zeromq-$ZEROMQ_VERSION.tar.gz 	&& tar -zxvf zeromq-$ZEROMQ_VERSION.tar.gz 	&& cd ./zeromq-$ZEROMQ_VERSION 	&& ./configure && make && make install 	&& ldconfig' returned a non-zero code: 8
make: *** [deploy] Error 1

部署的时候提示上面的错误，部署的机器是mac mini，我使用brew install zeromq，还是无法跳过此步骤，求帮忙解决~

**Comment by xudafeng** [comment]
@lylh 是在 docker 环境内部署的，可以解决下zeromq网络问题

**Comment by xudafeng** [comment]
@lylh macmini 你可以选择非 docker 部署，看makefile

**Comment by lylh** [comment]
@xudafeng  OK， 我看看 makefile

**Comment by xudafeng** [comment]
@lylh qq 群287162474

**Comment by lylh** [comment]
在安装zeromq时去download.zeromq.org下载，对方服务器已经没有download.zeromq.org域名了，看了原网站，目前安装包已经放在github上了，https://github.com/zeromq/zeromq4-1/releases/download/v-4.1.4/zeromq-4.1.4.tar.gz，@xudafeng   需要修改下Dockerfile

**Comment by xudafeng** [comment]
https://github.com/reliablejs/reliable-master/commit/bfec2ff727bfb35e5058832d801a88ff95c1d9e4
