### ISSUE TITLE
reliable-master 容器运行出错

### ISSUE THREAD

**Issue by xyc1121** [reliablejs/reliable-master#19]
reliable-master 一直处于restart状态，根据log看像是权限问题。
但是修改权限后也解决不了问题。
请提供帮助。
![image](https://cloud.githubusercontent.com/assets/19163799/16035642/c9758d42-324a-11e6-8776-e9c1d17afc37.png)

**Comment by sencho** [comment]
@xyc1121 查看一下docker ps容器是否正常？可以试试把master容器停止了，再把他删除，再用手动方式起动一个master;具体参数看这里http://macacajs.github.io/macaca/master-deployment.html    
Advanced Topics-Manually Launch.

**Comment by xyc1121** [comment]
@sencho 
谢谢你的回答。
尝试过删除容器，手动启动，还是同样的问题。

**Comment by sencho** [comment]
@xyc1121 你是把所有的容器都删除然后再手动起动吗？按照Advanced Topics-Manually Launch.来一个个起动，一共3个容器。我现在也是手动起动的，没再出现不断重启的问题了。

**Comment by xyc1121** [comment]
@sencho 
全部容器删除，再手动重启还是一样的错误。

**Comment by sencho** [comment]
@xyc1121 三个步骤我都测试过的，可以正常启动。另你可否上传你最新的docker容器和镜像截图，如果你按步骤操作应该只启动了3个容器，我上我的截图给你，你对比一下，再检查一遍操作步骤。

我的容器
```shell
CONTAINER ID        IMAGE                            COMMAND                  CREATED             STATUS              PORTS                    NAMES
e32ad3e29b45        reliablemaster_reliable-master   "make serve env=prod"    12 days ago         Up 12 days          0.0.0.0:8080->8080/tcp   reliable_master_prod
7329a5f93a2e        redis                            "docker-entrypoint.sh"   12 days ago         Up 12 days          6379/tcp                 reliable_redis_prod
53f8ef2a1312        mongo                            "/entrypoint.sh mongo"   12 days ago         Up 12 days          27017/tcp                reliable_mongo_prod
```

我的镜像
```shell
REPOSITORY                       TAG                 IMAGE ID            CREATED             SIZE
reliablemaster_reliable-master   latest              ed940ed7cbac        2 weeks ago         929 MB
redis                            latest              be9c5a746699        4 weeks ago         184.9 MB
mongo                            latest              a55d8a328b43        5 weeks ago         313.1 MB
node                             4.2.1               90bb496e949e        7 months ago        641.7 MB
```

**Comment by xyc1121** [comment]
@sencho 
容器：
![image](https://cloud.githubusercontent.com/assets/19163799/16065079/e31f1292-32d9-11e6-909e-4f7331169d52.png)
镜像：
![image](https://cloud.githubusercontent.com/assets/19163799/16065093/033b15b2-32da-11e6-8db8-2c642b3f6369.png)

**Comment by sencho** [comment]
@xyc1121 这样建议你重新make deploy

**Comment by xyc1121** [comment]
那之前装的images、容器都要删除吗？

**Comment by xyc1121** [comment]
@sencho 
重新make deploy，仍然有这个问题。
![image](https://cloud.githubusercontent.com/assets/19163799/16138677/933e9244-3472-11e6-905e-15a5feb71550.png)

**Comment by sencho** [comment]
@xyc1121 好明显是权限问题，你把reliable放到别的地方再运行，不要放在bin/目录下。

**Comment by xyc1121** [comment]
@sencho 
重新vi创建了bin下的3个文件后，就可以启动了。
