### ISSUE TITLE
hi,请教具体的用法

### ISSUE THREAD

**Issue by qileilove** [reliablejs/reliable-master#21]
master 和slave 都启动， master 用的docker  slave 用的本机。并且slave 已经连接到master上，我看到task配置只有repo和Branch，用的你们的macaca的demo 
https://github.com/macacajs/macaca-test-sample
请问该ci 怎么识别执行具体操作 需要在什么配置文件 配置信息？

**Comment by qileilove** [comment]
![Uploading image.png…]()

**Comment by qileilove** [comment]
![image](https://cloud.githubusercontent.com/assets/3895501/16068438/4f538e66-32f8-11e6-9d6d-0f7f2a0157fe.png)
![image](https://cloud.githubusercontent.com/assets/3895501/16068445/6cd362cc-32f8-11e6-8659-f83b31519cfd.png)

**Comment by sencho** [comment]
sample中的macaca-test目录就放有用例，实际执行的是slave，跑的是macaca

**Comment by qileilove** [comment]
@sencho 用例这个我知道，执行的肯定的slave，跑的也是macaca，我想了解的是比如像jenkins跑测试的话，你必须配置用例的目录，用什么去运行用例，比如junit，jasmine等，跑哪些用例等等，你的slave 运行的时候，肯定要配置要相应的环境，你跑android的话，你的sdk，java等，应该要有一个配置文件吧。 再说这个demo里面，有这么多测试
```

test-ios: install
	macaca doctor
	platform=ios macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js
test-ios-safari: install
	macaca doctor
	browser=safari macaca run --verbose -d ./macaca-test/macaca-mobile-browser-sample.test.js
test-android-chrome: install
	macaca doctor
	browser=chrome macaca run --verbose -d ./macaca-test/macaca-mobile-browser-sample.test.js
test-android: install
	macaca doctor
	platform=android macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js
test-pc:
	macaca install electron
	macaca doctor
	macaca run --verbose -d ./macaca-test/macaca-desktop-sample.test.js
travis-pc:
	${npm_bin}/macaca install electron
	${npm_bin}/macaca doctor
	${npm_bin}/macaca run -d ./macaca-test/macaca-desktop-sample.test.js --no-window
```
这个ci 怎么知道跑哪个？

**Comment by sencho** [comment]
@qileilove 测试目录暂时不可配置，只可以用macaca跑用例，用例都放在macaca-test目录下，你可以通过分多个任务，放在不同的分支check out下来。

**Comment by xudafeng** [comment]
测试目录可以通过 -d 配置
```
macaca -d ./test
```

**Comment by qileilove** [comment]
@xudafeng  
![image](https://cloud.githubusercontent.com/assets/3895501/16116620/8c8dab50-3400-11e6-8b19-69749a8937a2.png)
master log 里面 有个macaca yml file 请问这个文件是干嘛的？
还有 macaca -d ./test可以指定测试目录，但是ci 无法指定。 所以非常困惑 它是怎么识别不同平台的测试的，比如 ``` platform=android macaca run --verbose -d ./macaca-test/macaca-mobile-sample.test.js```
必须指定platform=android,那么ci那里怎么指定，他现在只能配置个repo。
 多谢有这么好的测试工具，但是文档真的太少了，尤其ci这里。 我可以用jenkins 或者bamboo ，travis-ci 等跑 但是你们这个更吸引我。

**Comment by sencho** [comment]
@qileilove 在用例里可以指定平台的，其实不用在启动命令的时候指定，这种使用方法可以在群里讨论，如果不是bug的话请关闭issue吧，谢谢。
