### ISSUE TITLE
在执行./reliable-master server -p 8080提示如下没有Cannot find module 'babel/register'

### ISSUE THREAD

**Issue by chengxuefeng** [reliablejs/reliable-master#22]
使用 npm install babel/register
－－－－－－－－－－－－－－－－－
ERR! Command failed: git clone --template=/Users/cxf/.npm/_git-remotes/_templates --mirror git@github.com:babel/register.git /Users/cxf/.npm/_git-remotes/git-github-com-babel-register-git-d0577442
npm ERR! Cloning into bare repository '/Users/cxf/.npm/_git-remotes/git-github-com-babel-register-git-d0577442'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.252.121' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cxf/Documents/git/reliable-master/bin/npm-debug.log
－－－－－－－－－－－－－－－
我查看了log如下
－－－－－－－－－－－－－－－
error node v4.4.5
48 error npm  v2.15.5
49 error code 128
50 error Command failed: git clone --template=/Users/cxf/.npm/_git-remotes/_templates --mirror git@github.com:babel/register.git /Users/cxf/.npm/_git-remotes/git-github-com-babel-register-git-d0577442
50 error Cloning into bare repository '/Users/cxf/.npm/_git-remotes/git-github-com-babel-register-git-d0577442'...
50 error Warning: Permanently added the RSA host key for IP address '192.30.252.121' to the list of known hosts.
50 error Permission denied (publickey).
50 error fatal: Could not read from remote repository.
50 error
50 error Please make sure you have the correct access rights
没有权限？
－－－－－－－－－－－－－－－－－－－－－－－－
由于刚接触node 和docker，看不太懂
我在执行了 make dploy后 并执行了那三个step，发现无法访问http://localhost:8080，所以才执行了 ./reliable-master server -p 8080。
四个绿色的图标均亮着

**Comment by xudafeng** [comment]
npm install

**Comment by chengxuefeng** [comment]
您好，在reliable-master目录下执行 make deploy  ，提示如下，是我网络的原因吗？ 还是我缺少安装了什么组建呀？
－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－－


npm info postinstall babel@5.6.23
npm ERR! Linux 4.4.12-boot2docker
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--registry=https://registry.npm.taobao.org"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE

npm ERR! zmq@2.13.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmq@2.13.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the zmq package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls zmq
npm ERR! There is likely additional logging output above.
npm info preuninstall zmq@2.13.0
npm info uninstall zmq@2.13.0
npm info postuninstall zmq@2.13.0

npm ERR! Please include the following file with any support request:
npm ERR!     /reliable-master/npm-debug.log
ERROR: Service 'reliable-master' failed to build: The command '/bin/sh -c npm install --registry=https://registry.npm.taobao.org' returned a non-zero code: 1
make: *** [deploy] Error 1
－－－－－－－－－－－－－－－－－

**Comment by sencho** [comment]
装了node 和npm没有

**Comment by chengxuefeng** [comment]
已经弄好了，是我们公司的网络的原因。。。涉及到敏感字。。。
感谢您的分享。。。
