### ISSUE TITLE
安装reliable-macaca-slave报错

### ISSUE THREAD

**Issue by xyc1121** [reliablejs/reliable-master#23]
W7下安装reliable-slave报错。
在C:\Users\Administrator\AppData\Roaming\npm\node_modules下没有生成reliable-slave。
请求帮助。

C:\Users\Administrator\AppData\Roaming\npm\node_modules\reliable-slave\node_modules\zmq>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
MSBUILD : error MSB3411: Could not load the Visual C++ component "VCBuild.exe". If the component is not installed, either 1) install the Microsoft Windows SDK for Windows Server 2008 and .NET Framework 3.5, or 2) install Microsoft Visual Studio 2008.  [C:\Users\Administrator\AppData\Roaming\npm\node_modules\reliable-slave\node_modules\zmq\build\binding.sln]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Administrator\AppData\Roaming\npm\node_modules\reliable-slave\node_modules\zmq
gyp ERR! node -v v5.4.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm WARN install:zmq@2.13.0 zmq@2.13.0 install: `node-gyp rebuild`
npm WARN install:zmq@2.13.0 Exit status 1

C:\Users\Administrator\AppData\Roaming\npm
└── (empty)

npm ERR! code 1

**Comment by xudafeng** [comment]
@xyc1121 windows做slave？

**Comment by xyc1121** [comment]
是的，不能部署吗？
reliable-master已经在W7已经部署好了。

**Comment by xudafeng** [comment]
能，只是这么做的不多。zmq装好了？

**Comment by xyc1121** [comment]
npm安装了，不知道能不能用。
![image](https://cloud.githubusercontent.com/assets/19163799/16334282/883877c8-3a32-11e6-9eb8-fb9a50ce5e41.png)

**Comment by sencho** [comment]
这种环境真没试过，同学如果成功了分享一下

**Comment by xudafeng** [comment]
@xyc1121 不推荐用这个系统做，做在docker里吧
