### ISSUE TITLE
Master一键部署的时候有些部分下载不了

### ISSUE THREAD

**Issue by if1else0** [reliablejs/reliable-master#3]
到这一步骤到时候卡住了 下载了一个晚上 没下载下来
![image](https://cloud.githubusercontent.com/assets/10397913/13866650/ac957ad6-ecf2-11e5-94f7-69ffa85dc903.png)

**Comment by jsenjoy** [comment]
docker 镜像源是国外的，是国内网络问题导致的，有空多试几遍看看。

**Comment by jsenjoy** [comment]
或者你可以考虑使用 Aliyun 镜像加速服务，参考这个文章：https://testerhome.com/topics/4406

**Comment by if1else0** [comment]
已经安装https://testerhome.com/topics/4406 做了  还是一样的 看来得多试几次了
