### ISSUE TITLE
master docker build exit with error"npm ERR! registry error parsing json

### ISSUE THREAD

**Issue by DavidRichard2016** [reliablejs/reliable-master#39]
Step 6 : RUN make build
 ---> Running in 5ec185e35fd7
npm ERR! registry error parsing json
npm ERR! registry error parsing json
npm ERR! registry error parsing json

i have try it for three times, it can not work anymore!
So ,do anyone have solution for this.
I use mac mini :10.11
docker:Version 1.12.1 (build: 12133)
2d5b4d9c3daa089e3869e6355a47dd96dbf39856

**Comment by brunoyang** [comment]
* [http://stackoverflow.com/questions/30787702/npm-err-registry-error-parsing-json-while-trying-to-install-cordova-for-ionic](http://stackoverflow.com/questions/30787702/npm-err-registry-error-parsing-json-while-trying-to-install-cordova-for-ionic)
* [https://github.com/npm/npm/issues/8536](https://github.com/npm/npm/issues/8536)

**Comment by misfitdavidl** [comment]
fixed , Maybe there were some errors with my network
