### ISSUE TITLE
Deploy with docker is recommended to use Dockerfile

### ISSUE THREAD

**Issue by henjue** [reliablejs/reliable-master#4]
Deploy with docker is recommended to use Dockerfile
This may be a lot better

**Comment by jsenjoy** [comment]
`docker-compose` is easy to use to run the server quickly. And you don't care about redis, mongodb.
In future, we will make up the reliable docker images for who wants to make their own redis or mongodb. And then you can take yourself configuration to run reliable.
Thank you!

**Comment by jsenjoy** [comment]
Close?

**Comment by henjue** [comment]
Yes, hope more and more perfect, more and more powerful!
